POST http://127.0.0.1:8080/queryByZip HTTP/1.1
content-type: application/json

{
    "zipCode": "98052"
}


###

POST http://127.0.0.1:8080/queryByState HTTP/1.1
content-type: application/json

{
    "state": "WA"
}